name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./target/release/vakfu.exe
          args: -fq
      - name: Upload the artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} ./target/release/vakfu.exe
